version: '3.8'

services:
  # PostgreSQL 数据库
  postgres:
    image: postgres:15-alpine
    container_name: fittracker-postgres-test
    environment:
      POSTGRES_DB: fittracker_test
      POSTGRES_USER: fittracker
      POSTGRES_PASSWORD: fittracker123
    ports:
      - "5433:5432"
    volumes:
      - postgres_test_data:/var/lib/postgresql/data
    networks:
      - fittracker-test-network
    restart: unless-stopped

  # Redis 缓存
  redis:
    image: redis:7-alpine
    container_name: fittracker-redis-test
    command: redis-server --appendonly yes
    ports:
      - "6380:6379"
    volumes:
      - redis_test_data:/data
    networks:
      - fittracker-test-network
    restart: unless-stopped

  # FitTracker Backend API (测试环境)
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: fittracker-backend-test
    environment:
      ENVIRONMENT: test
      PORT: 8081
      HOST: 0.0.0.0
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USER: fittracker
      DB_PASSWORD: fittracker123
      DB_NAME: fittracker_test
      DB_SSLMODE: disable
      REDIS_HOST: redis
      REDIS_PORT: 6379
      REDIS_PASSWORD: ""
      REDIS_DB: 0
      JWT_SECRET: fittracker-test-secret-key
      JWT_EXPIRES_IN: 24
    ports:
      - "8081:8081"
    depends_on:
      - postgres
      - redis
    networks:
      - fittracker-test-network
    restart: unless-stopped

volumes:
  postgres_test_data:
    driver: local
  redis_test_data:
    driver: local

networks:
  fittracker-test-network:
    driver: bridge
