name: fittracker
description: "FitTracker - 热血健身打卡社交应用"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  # UI 组件
  cupertino_icons: ^1.0.6
  material_design_icons_flutter: ^7.0.7296
  
  # 状态管理
  riverpod: ^2.4.9
  flutter_riverpod: ^2.4.9
  
  # 网络请求
  dio: ^5.4.0
  retrofit: ^4.0.3
  json_annotation: ^4.8.1
  
  # 本地存储
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  shared_preferences: ^2.2.2
  
  # 路由管理
  go_router: ^12.1.3
  
  # 图片处理
  image_picker: ^1.0.4
  cached_network_image: ^3.3.0
  
  # 图表
  fl_chart: ^0.66.0
  
  # 日期时间
  intl: ^0.19.0
  table_calendar: ^3.0.9
  
  # 权限管理
  permission_handler: ^11.1.0
  
  # 设备信息
  device_info_plus: ^9.1.1
  
  # 网络检测
  connectivity_plus: ^5.0.2
  
  # 加载动画
  shimmer: ^3.0.0
  lottie: ^2.7.0
  
  # 工具类
  uuid: ^4.2.1
  path_provider: ^2.1.2
  
  # 依赖注入
  get_it: ^7.6.7
  
  # 日志
  logger: ^2.0.2+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  
  # 代码生成
  build_runner: ^2.4.7
  json_serializable: ^6.7.1
  retrofit_generator: ^8.0.6
  hive_generator: ^2.0.1
  
  # 代码检查
  flutter_lints: ^3.0.1
  
  # 测试
  mockito: ^5.4.4
  integration_test:
    sdk: flutter
  
  # 图标生成
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true
  
  assets:
    - assets/images/
    - assets/icons/
    - assets/animations/
    - assets/fonts/

# 应用图标配置
flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icons/app_icon.png"
  min_sdk_android: 21
  web:
    generate: true
    image_path: "assets/icons/app_icon.png"
    background_color: "#1a1a1a"
    theme_color: "#ff6b35"
  