name: fittracker_test_app
description: "FitTracker 全链路按钮测试可视化应用"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  # UI 组件
  cupertino_icons: ^1.0.6
  
  # 状态管理
  flutter_riverpod: ^2.4.9
  
  # 网络请求
  dio: ^5.4.0
  
  # JSON处理
  json_annotation: ^4.8.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  
  # 代码检查
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true
